Show percentage switch
elementary/switchboard-plug-power pull request #193
Opened 2021-07-25 20:36 UTC by andirsun

fixes: #167

2021-07-26 09:18 UTC, jeremypw commented
Just a tip: If a PR changes the appearance then it is usual to include a screenshot of the changed appearance.

2021-07-27 23:19 UTC, cassidyjames requested changes
Just some code style nits

2021-07-27 23:19 UTC, cassidyjames commented on src/MainView.vala
> +        show_percent_label.xalign = 1;
Modern code style and whitespace between 

```suggestion
        var show_percent_label = new Gtk.Label (_("Show Percentage")) {
            halign = Gtk.Align.END,
            xalign = 1
        };

```

2021-07-27 23:19 UTC, cassidyjames commented on src/MainView.vala
> +        show_percent_switch.halign = Gtk.Align.START;
Modern code style

```suggestion
        var show_percent_switch = new Gtk.Switch () {
            halign = Gtk.Align.START
        };
```

2021-07-27 23:19 UTC, cassidyjames commented on src/MainView.vala
> +        main_grid.attach (show_percent_switch, 1, 0, 1, 1);
You can omit the span parameters as they default to 1

```suggestion
        main_grid.attach (show_percent_label, 0, 0);
        main_grid.attach (show_percent_switch, 1, 0);
```

2021-07-27 23:19 UTC, cassidyjames commented on src/MainView.vala
> +            main_grid.attach (als_switch, 1, 2, 1, 1);
Same as above; as long as we're updating this code, we can drop the implied `1` values.

```suggestion
            main_grid.attach (brightness_label, 0, 1);
            main_grid.attach (scale, 1, 1);
            main_grid.attach (als_label, 0, 2);
            main_grid.attach (als_switch, 1, 2);
```

2021-07-27 23:21 UTC, ryonakano commented on src/MainView.vala
> +        var show_percent_label = new Gtk.Label (_("Show Percentage")) {
```suggestion
        var show_percent_label = new Gtk.Label (_("Show percentage:")) {
```

For consistence with other labels in this view

2021-07-27 23:25 UTC, ryonakano commented
Now it looks like:

![Screenshot from 2021-07-28 08-24-58](https://user-images.githubusercontent.com/26003928/127240081-80318de6-284f-4d7c-bc7e-c5711fd605aa.png)

2021-07-27 23:26 UTC, ryonakano submitted a review, later dismissed
Works for me, I felt we may need a redesign using header labels though. But it should be done in another PR.

2021-08-06 05:13 UTC, ryonakano commented
I tested in a desktop machine that does not have any batteries and felt we should hide this switch if there are no batteries. So I added codes to check for battery existence.

@andirsun @jeremypw Would you check if this branch still works for you?

2021-08-06 14:33 UTC, jeremypw commented
Yeah, the "Single Exit Point" school of coding seems to have gone out of fashion ...

2021-08-06 23:11 UTC, ryonakano commented
The variable `present` is not used in the method for other purposes and I think the method is clean enough to notice two returns, so I removed it. Should I keep it as it is? 🤔

2021-08-07 02:34 UTC, andirsun commented
Yes its the same behavior.

2021-08-12 22:50 UTC, ryonakano approved these changes
Works as expected―the switch is hidden on the desktop and it appears and works on the laptop. Nice job!

2021-08-17 03:13 UTC, merged